-- V1: Criação das tabelas iniciais

CREATE TABLE TB_MISSOES (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
dificuldade VARCHAR(100) NOT NULL
);

CREATE TABLE TB_CADASTRO (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
img_url VARCHAR(255),
idade INT NOT NULL,
missoes_id BIGINT,
CONSTRAINT fk_missoes
FOREIGN KEY (missoes_id)
REFERENCES TB_MISSOES(id)
);
