-- V1: Criação das tabelas iniciais

CREATE TABLE TB_TAREFAS (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
prioridade VARCHAR(100) NOT NULL
);

CREATE TABLE TB_FUNCIONARIOS (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
idade INT NOT NULL,
tarefa_id BIGINT,
CONSTRAINT fk_tarefa
FOREIGN KEY (tarefa_id)
REFERENCES TB_TAREFAS(id)
);
